insert into items(name) values ('Item #1');
insert into items(name) values ('Item #2');
insert into items(name) values ('Item #3');
insert into items(name) values ('Item #4');
insert into items(name) values ('Item #5');
insert into items(name) values ('Item #6');
insert into items(name) values ('Item #7');
insert into items(name) values ('Item #8');
insert into items(name) values ('Item #9');